[workspace]
members = [
  "scripts/source/prepare_ci_pubsub",
  "src/batch",
  "src/bench",
  "src/cmd",
  "src/cmd_all",
  "src/common",
  "src/common/common_service",
  "src/compute",
  "src/connector",
  "src/ctl",
  "src/expr",
  "src/frontend",
  "src/frontend/planner_test",
  "src/java_binding",
  "src/meta",
  "src/object_store",
  "src/prost",
  "src/prost/helpers",
  "src/risedevtool",
  "src/rpc_client",
  "src/source",
  "src/sqlparser",
  "src/sqlparser/test_runner",
  "src/storage",
  "src/storage/backup",
  "src/storage/backup/cmd",
  "src/storage/compactor",
  "src/storage/hummock_sdk",
  "src/storage/hummock_test",
  "src/stream",
  "src/test_runner",
  "src/tests/compaction_test",
  "src/tests/regress",
  "src/tests/simulation",
  "src/tests/sqlsmith",
  "src/tracing",
  "src/udf",
  "src/utils/async_stack_trace",
  "src/utils/local_stats_alloc",
  "src/utils/pgwire",
  "src/utils/runtime",
  "src/utils/sync-point",
  "src/utils/workspace-config",
  "src/workspace-hack",
]

[workspace.package]
version = "0.2.0-alpha"
edition = "2021"
homepage = "https://github.com/risingwavelabs/risingwave"
keywords = ["sql", "database", "streaming"]
license = "Apache-2.0"
repository = "https://github.com/risingwavelabs/risingwave"

[workspace.dependencies]
aws-config = { version = "0.51", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-sdk-kinesis = { version = "0.21", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-sdk-s3 = { version = "0.21", default-features = false, features = ["rt-tokio","native-tls"] }
aws-sdk-sqs = { version = "0.21", default-features = false, features = ["rt-tokio", "native-tls"] }
aws-smithy-http = "0.51"
aws-smithy-types = "0.51"
aws-endpoint = "0.51"
aws-types = { version = "0.51", features = ["hardcoded-credentials"] }

[profile.dev]
lto = 'off'

[profile.release]
debug = true

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

# The profile used for CI in main branch.
# This profile inherits from the release profile, but turns on some checks and assertions for us to
# better catch bugs in CI.
[profile.ci-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true

# The profile used for CI in pull requests.
# External dependencies are built with optimization enabled, while crates in this workspace are built
# with `dev` profile and full debug info. This is a trade-off between build time and e2e test time.
[profile.ci-dev]
inherits = "dev"
incremental = false
[profile.ci-dev.package."*"] # external dependencies
opt-level = 1
[profile.ci-dev.package."tokio"]
opt-level = 3
[profile.ci-dev.package."async_stack_trace"]
opt-level = 3
[profile.ci-dev.package."indextree"]
opt-level = 3
[profile.ci-dev.package."task_stats_alloc"]
opt-level = 3

# The profile used for deterministic simulation tests in CI.
# The simulator can only run single-threaded, so optimization is required to make the running time
# reasonable. The optimization level is customized to speed up the build.
[profile.ci-sim]
inherits = "dev"
opt-level = 2

# Patch third-party crates for deterministic simulation.
[patch.crates-io]
quanta = { git = "https://github.com/madsim-rs/quanta.git", rev = "a819877" }
getrandom = { git = "https://github.com/madsim-rs/getrandom.git", rev = "cc95ee3" }
tokio-retry = { git = "https://github.com/madsim-rs/rust-tokio-retry.git", rev = "95e2fd3" }
tokio-postgres = { git = "https://github.com/madsim-rs/rust-postgres.git", rev = "87ca1dc" }
postgres-types = { git = "https://github.com/madsim-rs/rust-postgres.git", rev = "87ca1dc" }
