[package]
name = "risingwave_frontend"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arc-swap = "1"
assert-impl = "0.1"
async-trait = "0.1"
byteorder = "1.4"
bytes = "1"
clap = { version = "3", features = ["derive"] }
derivative = "2"
downcast-rs = "1.2"
dyn-clone = "1.0.4"
enum-as-inner = "0.5"
fixedbitset = "0.4.1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
itertools = "0.10"
maplit = "1"
md5 = "0.7.0"
num-integer = "0.1"
num-traits = "0.2"
parking_lot = "0.12"
parse-display = "0.6"
paste = "1"
pgwire = { path = "../utils/pgwire" }
pin-project-lite = "0.2"
postgres-types = { version = "0.2.4" }
prometheus = { version = "0.13", features = ["process"] }
prost = "0.11"
rand = "0.8"
risingwave_batch = { path = "../batch" }
risingwave_common = { path = "../common" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_connector = { path = "../connector" }
risingwave_expr = { path = "../expr" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_source = { path = "../source" }
risingwave_sqlparser = { path = "../sqlparser" }
risingwave_storage = { path = "../storage" }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
sha2 = "0.10.2"
smallvec = { version = "1.6.1", features = ["serde"] }
tempfile = "3"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tonic = { version = "0.2", package = "madsim-tonic" }
tracing = "0.1"
uuid = "1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
tempfile = "3"
