[package]
name = "risingwave_stream"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
async_stack_trace = { path = "../utils/async_stack_trace" }
auto_enums = { version = "0.7", features = ["futures"] }
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
crc32fast = "1"
dyn-clone = "1"
either = "1"
enum-as-inner = "0.5"
farmhash = "1"
fixedbitset = { version = "0.4", features = ["std"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
gen-iter = "0.3"
hyper = "0.14"
iter-chunks = "0.1"
itertools = "0.10"
local_stats_alloc = { path = "../utils/local_stats_alloc" }
lru = { git = "https://github.com/risingwavelabs/lru-rs.git", branch = "evict_by_timestamp" }
maplit = "1.0.2"
memcomparable = "0.1"
minitrace = "0.4"
minstant = "0.1"
multimap = "0.8"
num-traits = "0.2"
parking_lot = "0.12"
paste = "1"
pin-project = "1"
prometheus = { version = "0.13", features = ["process"] }
prost = "0.11"
rand = "0.8"
risingwave_common = { path = "../common" }
risingwave_connector = { path = "../connector" }
risingwave_expr = { path = "../expr" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_source = { path = "../source" }
risingwave_storage = { path = "../storage" }
serde = { version = "1", features = ["derive"] }
serde-value = "0.7"
serde_json = "1"
smallvec = "1"
static_assertions = "1"
task_stats_alloc = { path = "../utils/task_stats_alloc" }
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-metrics = "0.1.0"
tokio-stream = "0.1"
tonic = { version = "0.2", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tracing = "0.1"
tracing-futures = "0.2"
twox-hash = "1"
url = "2"

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = "0.5"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
risingwave_hummock_test = { path = "../storage/hummock_test" }
